### ISSUE TITLE
Trouble setting up base on example and testing it. 

### ISSUE THREAD

**Issue by stefanusz** [thallium205/xero#13]
Hi there, 

I'm having trouble setting this up and trying it out. I have created the private and public and uploaded it. 
I saw the different issues and change the iff(err) part from one of your issues. 

```javascript
var CONSUMER_KEY="my consumer key";
var CONSUMER_SECRET="my consumer secret";
var RSA_PRIVATE_KEY = require('fs').readFileSync('privatekey.pem');

var Xero = require('xero');

var xero = new Xero(CONSUMER_KEY, CONSUMER_SECRET, RSA_PRIVATE_KEY);
xero.call('GET', '/Users', null, function(err, json) {
        if (err) {
            console.error(err);
        }
        return res.json(200, json);
    });
```

After the above I just run node myfile.js and it gives me this bunch of errors of log is not defined. 
```
        return res.json(200, json);
               ^

ReferenceError: res is not defined
    at /Users/Stefanus/Desktop/Xero Try Out/xeroTestApi.js:12:16
    at /Users/Stefanus/node_modules/xero/index.js:47:24
    at /Users/Stefanus/node_modules/xero/node_modules/xml2js/lib/xml2js.js:381:22
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
```

Can I get some help in regards to this? Many thanks!

**Comment by andrew-wharton** [comment]
The example is in the context of responding to an HTTP request. ie.

```javascript
var express = require("express");
var Xero = require('xero');
var fs = require('fs');

var app = express();

var CONSUMER_KEY="my consumer key";
var CONSUMER_SECRET="my consumer secret";
var RSA_PRIVATE_KEY = fs.readFileSync(process.env.HOME + "/.ssh/id_rsa");
var xero = new Xero(CONSUMER_KEY, CONSUMER_SECRET, RSA_PRIVATE_KEY);

app.get('/', function (req, res) {
  xero.call('GET', '/Users', null, function(err, json) {
    if (err) {
      res.status(err.statusCode);
      res.write(JSON.stringify(err));
      res.end();
    } else {
      res.status(200);
      res.write(JSON.stringify(json));
      res.end();
    }
  });
});

app.listen(3000, function () {
  console.log("Listening...");
});
```
